<a href="https://colab.research.google.com/github/hyona-yu/RL_RS_study/blob/master/CollaborativeFiltering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import os
import ipywidgets
import traitlets
#####movielen latest small 사용 #####
#data_dir = './ml-latest-small/'
data_dir  = os.getcwd() + "/"
print(data_dir)
movies_csv = pd.read_csv(data_dir + "movies.csv")
links_csv = pd.read_csv(data_dir + "links.csv")
ratings_csv = pd.read_csv(data_dir + "ratings.csv")
tags_csv = pd.read_csv(data_dir + "tags.csv")

/content/


In [0]:
movies_csv.head()
#links_csv.head()
#tags_csv.head()
#ratings_csv.head()

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [0]:
len(movies_csv)

9742

In [0]:
movie2rating = pd.merge(movies_csv, ratings_csv) #같은 column을 대상으로 합병
movie2rating = movie2rating.drop(columns = ['title', 'genres', 'timestamp'])
print(len(movie2rating))
movie2rating.head()

100836


movieId  userId  rating
0        1       1     4.0
1        1       5     4.0
2        1       7     4.5
3        1      15     2.5
4        1      17     4.5

In [0]:
movies_csv['genres']

0       Adventure|Animation|Children|Comedy|Fantasy
1                        Adventure|Children|Fantasy
2                                    Comedy|Romance
3                              Comedy|Drama|Romance
4                                            Comedy
                           ...                     
9737                Action|Animation|Comedy|Fantasy
9738                       Animation|Comedy|Fantasy
9739                                          Drama
9740                               Action|Animation
9741                                         Comedy
Name: genres, Length: 9742, dtype: object

In [0]:
#https://www.kaggle.com/manisha1409raj/recommender-system-collaborative-filtering 참조
rating = ratings_csv.pivot_table(index = ['movieId'], columns = ['userId'], values ='rating') #pivot table로 데이터 재구조가능.
rating.fillna(0, inplace = True) #inplace = True를 해야 적용됨.
rating.head()

userId   1    2    3    4    5    6    7    ...  604  605  606  607  608  609  610
movieId                                     ...                                   
1        4.0  0.0  0.0  0.0  4.0  0.0  4.5  ...  3.0  4.0  2.5  4.0  2.5  3.0  5.0
2        0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...  5.0  3.5  0.0  0.0  2.0  0.0  0.0
3        4.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  0.0  0.0  0.0  0.0  2.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  3.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  3.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 610 columns]

In [0]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(movie2rating[:1000])
sim
sim_matrix = pd.DataFrame(sim)
sim_matrix

0         1         2    ...       997       998       999
0    1.000000  0.800132  0.731163  ...  0.255440  0.254717  0.256632
1    0.800132  1.000000  0.994136  ...  0.783817  0.783389  0.784649
2    0.731163  0.994136  1.000000  ...  0.845054  0.844717  0.845827
3    0.402123  0.870755  0.917935  ...  0.987828  0.987731  0.988053
4    0.481737  0.911072  0.950000  ...  0.969278  0.969159  0.969693
..        ...       ...       ...  ...       ...       ...       ...
995  0.252237  0.781604  0.843025  ...  0.999978  0.999970  0.999953
996  0.259811  0.786541  0.847328  ...  0.999985  0.999976  0.999978
997  0.255440  0.783817  0.845054  ...  1.000000  0.999999  0.999995
998  0.254717  0.783389  0.844717  ...  0.999999  1.000000  0.999997
999  0.256632  0.784649  0.845827  ...  0.999995  0.999997  1.000000

[1000 rows x 1000 columns]

In [0]:
try : 
  user_inp = 'Jumanji (1995)'
  inp = movies_csv[movies_csv['title']==user_inp].index.tolist()
  inp = inp[0]
  movies_csv['similarity'] = sim_matrix.iloc[inp]
  print(movies_csv.head())
except:
  print("No")

   movieId  ... similarity
0        1  ...   0.800132
1        2  ...   1.000000
2        3  ...   0.994136
3        4  ...   0.870755
4        5  ...   0.911072

[5 rows x 4 columns]


In [0]:
#####Matrix Factorization 구현
# https://yamalab.tistory.com/92 참조
#R : original rating data matrix
#Nu : number of users
#Ni : number of items
R = rating.values #이러면 행렬로만 표현
num_item = len(movies_csv) #9742
num_user = ratings_csv['userId'].tolist()[-1] #610
nf = 50 #dimension of laten factor


In [0]:
print(R.shape)


(9724, 610)


(100, 610)

In [0]:
class MatrixFactorization():
    def __init__(self, R, k, learning_rate, reg_param, epochs, verbose=False):
        """
        :param R: rating matrix
        :param k: latent parameter
        :param learning_rate: alpha on weight update
        :param reg_param: beta on weight update
        :param epochs: training epochs
        :param verbose: print status
        """

        self._R = R
        self._num_users, self._num_items = R.shape
        self._k = k
        self._learning_rate = learning_rate
        self._reg_param = reg_param
        self._epochs = epochs
        self._verbose = verbose


    def fit(self):
        """
        training Matrix Factorization : Update matrix latent weight and bias

        참고: self._b에 대한 설명
        - global bias: input R에서 평가가 매겨진 rating의 평균값을 global bias로 사용
        - 정규화 기능. 최종 rating에 음수가 들어가는 것 대신 latent feature에 음수가 포함되도록 해줌.

        :return: training_process
        """

        # init latent features
        self._P = np.random.normal(size=(self._num_users, self._k))
        self._Q = np.random.normal(size=(self._num_items, self._k))

        # init biases
        self._b_P = np.zeros(self._num_users)
        self._b_Q = np.zeros(self._num_items)
        self._b = np.mean(self._R[np.where(self._R != 0)]) #np.where : 배열 안의 조건값에 해당하는거 다 포함해줌.

        # train while epochs
        self._training_process = []
        for epoch in range(self._epochs):

            # rating이 존재하는 index를 기준으로 training
            for i in range(self._num_users):
                for j in range(self._num_items):
                    if self._R[i, j] > 0:
                        self.gradient_descent(i, j, self._R[i, j])
            cost = self.cost()
            self._training_process.append((epoch, cost))

            # print status
            if self._verbose == True and ((epoch + 1) % 10 == 0):
                print("Iteration: %d ; cost = %.4f" % (epoch + 1, cost))
        return self.get_complete_matrix()


    def cost(self):
        """
        compute root mean square error
        :return: rmse cost
        """

        # xi, yi: R[xi, yi]는 nonzero인 value를 의미한다.
        # 참고: http://codepractice.tistory.com/90
        xi, yi = self._R.nonzero() # 0이아닌값 index를 반환. 여기선 이차원배열이니깐 이런가보다.
        predicted = self.get_complete_matrix()
        cost = 0
        for x, y in zip(xi, yi):
            cost += pow(self._R[x, y] - predicted[x, y], 2) #제곱. 음수 없어주려고 그런듯?
        return np.sqrt(cost) / len(xi)


    def gradient(self, error, i, j):
        """
        gradient of latent feature for GD

        :param error: rating - prediction error
        :param i: user index
        :param j: item index
        :return: gradient of latent feature tuple
        """

        dp = (error * self._Q[j, :]) - (self._reg_param * self._P[i, :])
        dq = (error * self._P[i, :]) - (self._reg_param * self._Q[j, :])
        return dp, dq


    def gradient_descent(self, i, j, rating):
        """
        graident descent function

        :param i: user index of matrix
        :param j: item index of matrix
        :param rating: rating of (i,j)
        """

        # get error
        prediction = self.get_prediction(i, j)
        error = rating - prediction

        # update biases
        self._b_P[i] += self._learning_rate * (error - self._reg_param * self._b_P[i])
        self._b_Q[j] += self._learning_rate * (error - self._reg_param * self._b_Q[j])

        # update latent feature
        dp, dq = self.gradient(error, i, j)
        self._P[i, :] += self._learning_rate * dp
        self._Q[j, :] += self._learning_rate * dq


    def get_prediction(self, i, j):
        """
        get predicted rating: user_i, item_j
        :return: prediction of r_ij
        """
        return self._b + self._b_P[i] + self._b_Q[j] + self._P[i, :].dot(self._Q[j, :].T)


    def get_complete_matrix(self):
        """
        computer complete matrix PXQ + P.bias + Q.bias + global bias

        - PXQ 행렬에 b_P[:, np.newaxis]를 더하는 것은 각 열마다 bias를 더해주는 것
        - b_Q[np.newaxis:, ]를 더하는 것은 각 행마다 bias를 더해주는 것
        - b를 더하는 것은 각 element마다 bias를 더해주는 것

        - newaxis: 차원을 추가해줌. 1차원인 Latent들로 2차원의 R에 행/열 단위 연산을 해주기위해 차원을 추가하는 것.

        :return: complete matrix R^
        """
        return self._b + self._b_P[:, np.newaxis] + self._b_Q[np.newaxis:, ] + self._P.dot(self._Q.T)


    def print_results(self):
        """
        print fit results
        """

        print("User Latent P:")
        print(self._P)
        print("Item Latent Q:")
        print(self._Q.T)
        print("P x Q:")
        print(self._P.dot(self._Q.T))
        print("bias:")
        print(self._b)
        print("User Latent bias:")
        print(self._b_P)
        print("Item Latent bias:")
        print(self._b_Q)
        print("Final R matrix:")
        print(self.get_complete_matrix())
        print("Final RMSE:")
        print(self._training_process[self._epochs-1][1])

In [0]:
factorizer = MatrixFactorization(R[:100,:100], k=3, learning_rate=0.01, reg_param=0.01, epochs=300, verbose=True)
new_R  = factorizer.fit()
#factorizer.print_results()

Iteration: 10 ; cost = 0.0314
Iteration: 20 ; cost = 0.0272
Iteration: 30 ; cost = 0.0252
Iteration: 40 ; cost = 0.0239
Iteration: 50 ; cost = 0.0229
Iteration: 60 ; cost = 0.0220
Iteration: 70 ; cost = 0.0214
Iteration: 80 ; cost = 0.0208
Iteration: 90 ; cost = 0.0203
Iteration: 100 ; cost = 0.0199
Iteration: 110 ; cost = 0.0196
Iteration: 120 ; cost = 0.0192
Iteration: 130 ; cost = 0.0189
Iteration: 140 ; cost = 0.0187
Iteration: 150 ; cost = 0.0184
Iteration: 160 ; cost = 0.0182
Iteration: 170 ; cost = 0.0179
Iteration: 180 ; cost = 0.0177
Iteration: 190 ; cost = 0.0175
Iteration: 200 ; cost = 0.0173
Iteration: 210 ; cost = 0.0172
Iteration: 220 ; cost = 0.0170
Iteration: 230 ; cost = 0.0169
Iteration: 240 ; cost = 0.0167
Iteration: 250 ; cost = 0.0166
Iteration: 260 ; cost = 0.0165
Iteration: 270 ; cost = 0.0164
Iteration: 280 ; cost = 0.0163
Iteration: 290 ; cost = 0.0162
Iteration: 300 ; cost = 0.0161


In [0]:
print(new_R[:5,:5])
print(R[:5,:5])

[[4.29436717 4.82867811 1.80246125 1.0027213  3.71222304]
 [4.31826305 3.91412172 3.1342571  2.12912541 3.64636337]
 [3.81222571 2.86356107 2.52045444 1.76559182 3.36323015]
 [3.92912781 4.74959935 2.02872073 1.03841445 3.13441383]
 [3.74935103 3.8195622  1.32768369 0.84392464 3.38127534]]
[[4. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
